apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdnd5MTh1dy5jMS5kZTEuY29udGFpbmVyLXJlZ2lzdHJ5Lm92aC5uZXQiOnsidXNlcm5hbWUiOiJmbkVYdkFqUEpuIiwicGFzc3dvcmQiOiI4eEhhNnAwNzUzMTI0OVBSIiwiYXV0aCI6IlptNUZXSFpCYWxCS2JqbzRlRWhoTm5Bd056VXpNVEkwT1ZCUyJ9fX0=
kind: Secret
metadata:
  name: ovh-registry-secret
  namespace: credit-enforcement
type: kubernetes.io/dockerconfigjson
