package com.finx.dmsservice.domain.enums;

public enum NoticeType {
    DEMAND_NOTICE,
    LEGAL_NOTICE,
    RECALL_NOTICE,
    SETTLEMENT_OFFER,
    PAYMENT_REMINDER,
    FINAL_WARNING,
    ARBITRATION_NOTICE,
    POSSESSION_NOTICE,
    AUCTION_NOTICE,
    LOAN_RECALL,
    NPA_NOTICE,
    SARFAESI_13_2,
    SARFAESI_13_4,
    SYMBOLIC_POSSESSION,
    PHYSICAL_POSSESSION,
    OTHER
}
