CREATE TABLE IF NOT EXISTS customers (
    id BIGSERIAL PRIMARY KEY,
    customer_code VARCHAR(50) UNIQUE NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    mobile_number VARCHAR(15),
    alternate_mobile VARCHAR(15),
    email VARCHAR(100),
    alternate_email VARCHAR(100),
    address VARCHAR(500),
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(10),
    pan_number VARCHAR(20),
    aadhar_number VARCHAR(20),
    date_of_birth DATE,
    gender VARCHAR(10),
    occupation VARCHAR(100),
    customer_type VARCHAR(20) DEFAULT 'INDIVIDUAL',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan_details (
    id BIGSERIAL PRIMARY KEY,
    loan_account_number VARCHAR(50) UNIQUE NOT NULL,
    bank_code VARCHAR(50),
    product_code VARCHAR(50),
    product_type VARCHAR(100),
    primary_customer_id BIGINT NOT NULL,
    co_borrower_customer_id BIGINT,
    guarantor_customer_id BIGINT,
    loan_disbursement_date DATE,
    loan_maturity_date DATE,
    principal_amount DECIMAL(15,2),
    interest_amount DECIMAL(15,2),
    penalty_amount DECIMAL(15,2),
    total_outstanding DECIMAL(15,2),
    interest_rate DECIMAL(5,2),
    tenure_months INTEGER,
    emi_amount DECIMAL(15,2),
    dpd INTEGER,
    bucket VARCHAR(10),
    due_date DATE,
    source_system VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_loan_primary_customer FOREIGN KEY (primary_customer_id) REFERENCES customers(id),
    CONSTRAINT fk_loan_co_borrower FOREIGN KEY (co_borrower_customer_id) REFERENCES customers(id),
    CONSTRAINT fk_loan_guarantor FOREIGN KEY (guarantor_customer_id) REFERENCES customers(id)
);

CREATE TABLE IF NOT EXISTS cases (
    id BIGSERIAL PRIMARY KEY,
    case_number VARCHAR(50) UNIQUE NOT NULL,
    external_case_id VARCHAR(100),
    loan_id BIGINT NOT NULL,
    case_status VARCHAR(20) DEFAULT 'UNALLOCATED',
    case_priority VARCHAR(20) DEFAULT 'MEDIUM',
    case_opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    case_closed_at TIMESTAMP,
    case_closure_reason VARCHAR(100),
    allocated_to_user_id BIGINT,
    allocated_to_agency_id BIGINT,
    allocated_at TIMESTAMP,
    geography_code VARCHAR(50),
    city_code VARCHAR(50),
    state_code VARCHAR(50),
    ptp_date DATE,
    ptp_amount DECIMAL(15,2),
    ptp_status VARCHAR(20),
    next_followup_date DATE,
    source_type VARCHAR(20),
    source_file_name VARCHAR(255),
    import_batch_id VARCHAR(100),
    collection_cycle VARCHAR(50),
    is_archived BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_cases_loan FOREIGN KEY (loan_id) REFERENCES loan_details(id)
);

CREATE TABLE IF NOT EXISTS case_batches (
    id BIGSERIAL PRIMARY KEY,
    batch_id VARCHAR(100) UNIQUE NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    total_cases INTEGER DEFAULT 0,
    valid_cases INTEGER DEFAULT 0,
    invalid_cases INTEGER DEFAULT 0,
    duplicate_cases INTEGER DEFAULT 0,
    uploaded_by VARCHAR(255),
    file_name VARCHAR(500),
    file_path VARCHAR(1000),
    validation_job_id VARCHAR(100),
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS batch_errors (
    id BIGSERIAL PRIMARY KEY,
    batch_id VARCHAR(100) NOT NULL,
    row_number INTEGER,
    external_case_id VARCHAR(100),
    error_type VARCHAR(50),
    error_message TEXT,
    field_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
