INSERT INTO master_data (data_type, code, value, parent_code, display_order, is_active, metadata) VALUES
('BANK', 'HDFC', 'HDFC Bank', NULL, 1, TRUE, '{"region":"PAN_INDIA"}'),
('PRODUCT', 'PERSONAL_LOAN', 'Personal Loan', NULL, 1, TRUE, '{"loan_type":"UNSECURED"}'),
('LOCATION', 'MH', 'Maharashtra', NULL, 1, TRUE, '{"capital":"Mumbai"}'),
('DPD_BUCKET', '0-7', '0-7 Days', NULL, 1, TRUE, '{"severity": "LOW", "bucket_type": "EARLY", "min_dpd": 0, "max_dpd": 7}'),
('DISPOSITION', 'CONNECTED', 'Call Connected', NULL, 1, TRUE, '{"category": "SUCCESS", "requires_followup": false}'),
('PAYMENT_METHOD', 'CASH', 'Cash', NULL, 1, TRUE, '{"deposit_required": true, "sla_hours": 24, "reconciliation": "MANUAL"}'),
('PAYMENT_METHOD', 'PAYMENT_LINK', 'Payment Link', NULL, 9, TRUE, '{"instant": true, "gateway_required": true, "reconciliation": "AUTO"}'),
('NOTICE_TYPE', 'LEGAL', 'Legal Notice', NULL, 1, TRUE, '{"severity": "HIGH", "legal_binding": true, "min_dpd": 90}'),
('NOTICE_TYPE', 'SETTLEMENT', 'Settlement Notice', NULL, 5, TRUE, '{"severity": "MEDIUM", "legal_binding": false, "min_dpd": 45}'),
('DISPATCH_METHOD', 'SPEED_POST', 'Speed Post', NULL, 2, TRUE, '{"tracking": true, "pod_available": true, "cost_per_notice": 35, "delivery_days": 3}'),
('DISPATCH_METHOD', 'COURIER', 'Courier', NULL, 3, TRUE, '{"tracking": true, "pod_available": true, "cost_per_notice": 60, "delivery_days": 2}'),
('CASE_STATUS', 'UNALLOCATED', 'Unallocated', NULL, 1, TRUE, '{"description": "Case not yet assigned to collector", "active": true}'),
('CASE_STATUS', 'ALLOCATED', 'Allocated', NULL, 2, TRUE, '{"description": "Case assigned to collector", "active": true}'),
('LANGUAGE', 'en', 'English', NULL, 1, TRUE, '{"native_name": "English", "iso_code": "en"}'),
('LANGUAGE', 'hi', 'Hindi', NULL, 2, TRUE, '{"native_name": "हिन्दी", "iso_code": "hi"}'),
('LANGUAGE', 'mr', 'Marathi', NULL, 3, TRUE, '{"native_name": "मराठी", "iso_code": "mr"}'),
('LANGUAGE', 'gu', 'Gujarati', NULL, 4, TRUE, '{"native_name": "ગુજરાતી", "iso_code": "gu"}'),
('LANGUAGE', 'ta', 'Tamil', NULL, 5, TRUE, '{"native_name": "தமிழ்", "iso_code": "ta"}'),
('LANGUAGE', 'te', 'Telugu', NULL, 6, TRUE, '{"native_name": "తెలుగు", "iso_code": "te"}'),
('LANGUAGE', 'kn', 'Kannada', NULL, 7, TRUE, '{"native_name": "ಕನ್ನಡ", "iso_code": "kn"}'),
('LANGUAGE', 'ml', 'Malayalam', NULL, 8, TRUE, '{"native_name": "മലയാളം", "iso_code": "ml"}'),
('LANGUAGE', 'bn', 'Bengali', NULL, 9, TRUE, '{"native_name": "বাংলা", "iso_code": "bn"}'),
('LANGUAGE', 'pa', 'Punjabi', NULL, 10, TRUE, '{"native_name": "ਪੰਜਾਬੀ", "iso_code": "pa"}');
